POST http://localhost:3000/register
Content-Type : application/json
{
  "username": "christopher_phillips",
  "name" : "chris phillips",
  "password": "christy@123",
  "gender" : "Male",
  "location" : "Denroite"
###

POST http://localhost:3000/login/
Content-Type : application/json
{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###

GET http://localhost:3000/states/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y



###


GET http://localhost:3000/states/2/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y

###

POST http://localhost:3000/districts/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y
Content-Type : application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/9/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y


###


DELETE http://localhost:3000/districts/1/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y


PUT http://localhost:3000/districts/5/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y
Content-Type : application/json
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


###

GET http://localhost:3000/states/4/stats/
Authorization : Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.BbSVGcgUJQwsweFwJDIwhrdparHFtt6tqX7ckFS4A6Y
